### Installation of Numpy Library

In [29]:
!pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Numpy

Python lists are : 
 - Flexible but slowfor numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use numpy?
- Fast than pure python for numerical computation
- Vectorized operation (no explicit loops)
- Broadcasting (operate on arrays of different shape)
- Memory efficient
- Comes with powerful linear algebra, random tools etc

Use of numpy :
- Scientific python

In [1]:
import numpy as np

# creating arrays in numpy



### 1. np.array()

In [2]:
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr1

array([1, 2, 3, 4])

In [5]:
type(arr1[0])

numpy.int64

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
arr2[0]

array([1, 2, 3])

In [9]:
arr2[0][2]

np.int64(3)

In [10]:
arr2[1][2]

np.int64(6)

In [13]:
arr3=np.array([1,2,3,"Hello"])
print(arr3)
print(type(arr3))

['1' '2' '3' 'Hello']
<class 'numpy.ndarray'>


In [14]:
print(type(arr3[1]))

<class 'numpy.str_'>


In [17]:
arr4=np.array([1,2,3],dtype=np.int8)
print(type(arr4))

<class 'numpy.ndarray'>


In [18]:
print(type(arr4[0]))

<class 'numpy.int8'>


In [19]:
arr5=np.array([1,2,3,"Hello"],dtype=np.float16)

ValueError: could not convert string to float: 'Hello'

In [ ]:
arr6=np.array([1,2,3,"10"],dtype=np.float16)
arr6

<class 'numpy.float16'>


In [28]:
print(type(arr6[3]))

<class 'numpy.float16'>


### 2. np.arange(start, stop, step)