# NumPy

NumPy (Numerical Python) is a fundamental library for numerical computing in Python.  
It provides a powerful N-dimensional array object (`ndarray`) and tools for working with numerical data efficiently.

## Key Features
- Fast and memory-efficient arrays  
- Vectorized operations (no need for explicit loops)  
- Broadcasting support  
- Built-in mathematical and statistical functions  
- Linear algebra, random number generation, and Fourier transforms  

## Why NumPy is Important
- Forms the base of libraries like Pandas, SciPy, and Scikit-learn  
- Essential for data science, machine learning, and scientific computing  
- Handles large datasets much faster than Python lists  


In [153]:
import numpy as np

# creating arrays in numpy



### 1. np.array()

In [154]:
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [155]:
arr1

array([1, 2, 3, 4])

In [156]:
type(arr1[0])

numpy.int64

In [157]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [158]:
arr2[0]

array([1, 2, 3])

In [159]:
arr2[0][2]

np.int64(3)

In [160]:
arr2[1][2]

np.int64(6)

In [161]:
arr3=np.array([1,2,3,"Hello"])
print(arr3)
print(type(arr3))

['1' '2' '3' 'Hello']
<class 'numpy.ndarray'>


In [162]:
print(type(arr3[1]))

<class 'numpy.str_'>


In [163]:
arr4=np.array([1,2,3],dtype=np.int8)
print(type(arr4))

<class 'numpy.ndarray'>


In [164]:
print(type(arr4[0]))

<class 'numpy.int8'>


In [165]:
arr5=np.array([1,2,3,"Hello"],dtype=np.float16)

ValueError: could not convert string to float: 'Hello'

In [ ]:
arr6=np.array([1,2,3,"10"],dtype=np.float16)
arr6

array([ 1.,  2.,  3., 10.], dtype=float16)

In [ ]:
print(type(arr6[3]))

<class 'numpy.float16'>


### 2. np.arange(start, stop, step)

In [ ]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [ ]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [ ]:
np_linespace_1=np.linspace(1,100,4)
print(np_linespace_1)
print(type(np_linespace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [ ]:
np_linespace_2=np.linspace(1,10,10)
print(np_linespace_2)
print(type(np_linespace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [ ]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
for i in np.linspace(1,10,10,dtype=np.int8):
    print(i)

1
2
3
4
5
6
7
8
9
10


### 4. np.zeros(shape)

shape -> shape of matrix

In [ ]:
npz_1=np.zeros(5)
npz_1

array([0., 0., 0., 0., 0.])

In [ ]:
npz_2=np.zeros((5,5),dtype=np.int8)
print(npz_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
npz_2=np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
npz_3=np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
npz_3.ndim

3

### 5. np.ones(shape)

shape -> shape of matrix

In [ ]:
np0=np.ones((2,3))
print(np0)

[[1. 1. 1.]
 [1. 1. 1.]]


### 6. np.full(shape, fill_value)

shape -> shape of matrix

In [ ]:
npf_1=np.full((2,3),10)
print(npf_1)

[[10 10 10]
 [10 10 10]]


### 7. np.eye(shape)

shape -> shape of matrix

- does not exist in 1D
- min of 2D,shape

In [ ]:
npe=np.eye(3)
npe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### 8. np.empty(shape)

In [ ]:
np.empty((2,2),dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [ ]:
np.empty((2,2),dtype=np.float16)

array([[0.   , 0.   ],
       [0.   , 1.984]], dtype=float16)

### 9. np.random.rand(shape)

random values between 0 and 1

- ML weights random initialization

In [ ]:
np.random.rand(2,6)

array([[0.88711996, 0.08119716, 0.10945374, 0.24029216, 0.10164623,
        0.74741933],
       [0.70999079, 0.86367693, 0.23294492, 0.66504095, 0.38241297,
        0.91987207]])

In [ ]:
# 1 D --> vector

# Numpy Array attributes

### 1. ndarray.shape

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


### 2. ndarray.ndim

In [ ]:
print(arr.ndim)

2


### 3. ndarray.size

Returns the total number of elements in the array.

In [ ]:
print(arr.size)

6


### 4. ndarray.dtype

Tells the data type of the array elements.

In [ ]:
print(arr.dtype)

int64


### 5. ndarray.itemsize

Returns the size in bytes of one element.

1 byte --> 8 bit

int8 --> 8 bit

int64 --> int8 * 8 --> int64

In [ ]:
print(arr.itemsize)

8


### 6. ndarray.nbytes
Total number of bytes consumed by the array.

In [ ]:
print(arr.nbytes)

48


### 7. ndarray.T

Returns the transpose of the array.

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)


In [ ]:
reshaped_1=arr.reshape(2,3)
print(reshaped_1)
print(reshaped_1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
reshaped_2=arr.reshape(3,2)
print(reshaped_2)
print(reshaped_2.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
reshaped_3=arr.reshape(1,6)
print(reshaped_3)
print(reshaped_3.ndim)

[[1 2 3 4 5 6]]
2


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(arr1.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


What reshape(3, -1) Means

3 → You are forcing the array to have 3 rows.

-1 → NumPy automatically calculates the number of columns.

-1 is not magic

In [ ]:
arr2=arr1.reshape(3,-1)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
arr3=arr1.reshape(-1,3)
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
arr4=arr1.reshape(2,-1)
print(arr4)
print(arr4.shape)


ValueError: cannot reshape array of size 9 into shape (2,newaxis)

### 2. ravel() 

Flatten into 1D (returns a view)

Fast and memory-efficient.

Changes reflect in the original array (if no copy made).

In [ ]:
a=np.array([[1,2],[3,4]])

In [ ]:
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
print(a.ravel())

[1 2 3 4]


In [ ]:
print(a)

[[1 2]
 [3 4]]


In [ ]:
a_reval=a.ravel()
print(a_reval)
print(id(a))
print(id(a.ravel()))
print(id(a_reval))

[1 2 3 4]
2008818723952
2008818907824
2008818908880


In [ ]:
print("Data Address of 'a' : ",a.__array_interface__['data'][0])

Data Address of 'a' :  2008283247648


In [ ]:
print("Data Interfrence of Ravel a :",a.ravel().__array_interface__['data'][0])

Data Interfrence of Ravel a : 2008283247648


In [ ]:
print("Data Interfrence of Ravel a : ",a_reval.__array_interface__['data'][0])

Data Interfrence of Ravel a :  2008283247648


In [ ]:
a[0][0]=11

In [ ]:
a

array([[11,  2],
       [ 3,  4]])

In [ ]:
print(a_reval)

[11  2  3  4]


### 3. flatten()

Flatten into 1D (returns a copy)

In [ ]:
a

array([[11,  2],
       [ 3,  4]])

In [ ]:
b=a.flatten()

In [ ]:
b

array([11,  2,  3,  4])

In [ ]:
print("Data Interfrence of a : ",a.__array_interface__['data'][0])
print("Data Interfrence of b : ",b.__array_interface__['data'][0])

Data Interfrence of a :  2008283247648
Data Interfrence of b :  2008283244960


### 4. resize()

Resize Array In-place

Unlike reshape(), it can change total size. Data may be truncated or padded with zeros.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
a.resize(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.resize(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.resize(3,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.resize((3,3),refcheck=False)
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

### 5. squeeze()

Remove single-dimensional axes

Useful for removing extra dimensions from image or model output shapes like (1, 28, 28, 1)

In [ ]:
a=np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [ ]:
b=a.squeeze()

In [ ]:
print(b)
print(b.shape)

[1 2 3]
(3,)


| Function        | Purpose                        | In-place | Returns Copy/View  |
| --------------- | ------------------------------ | -------- | ------------------ |
| `reshape()`     | Change shape (same size)       | ❌        | View (if possible) |
| `resize()`      | Resize array (can change size) | ✅        | None               |
| `ravel()`       | Flatten array (1D)             | ❌        | View               |
| `flatten()`     | Flatten array (1D)             | ❌        | Copy               |
| `squeeze()`     | Remove dimensions of size 1    | ❌        | New array          |


# Indexing and Slicing in NumPy — Beginner to Advanced

###  1. Basic Indexing (1D Arrays)

Slicing syntax: array[start:stop:step]

In [ ]:
arr=np.array([10,20,30,40,50])

In [ ]:
print(arr[0])

10


In [ ]:
print(arr[-1])

50


In [ ]:
print(arr[4])

50


In [ ]:
print(arr[1:4])

[20 30 40]


In [ ]:
print(arr[1:-1])

[20 30 40]


In [ ]:
print(arr[0:3])

[10 20 30]


In [ ]:
print(arr[:3])

[10 20 30]


In [ ]:
print(arr[0:5:2])

[10 30 50]


In [ ]:
print(arr[::2])

[10 30 50]


In [ ]:
print(arr[::-1])

[50 40 30 20 10]


In [ ]:
list_1=[1,2,3,4,5,6,7]
list_1[::-1]

[7, 6, 5, 4, 3, 2, 1]

### 2. Indexing in 2D Arrays

In [ ]:
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
mat[0][1]

np.int64(2)

In [ ]:
mat[0,1]

np.int64(2)

In [ ]:
mat[:,2]

array([3, 6, 9])

In [ ]:
mat[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
mat[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 3. Boolean Indexing

In [ ]:
arr=np.array([5,10,15,20,25])

In [ ]:
l=[]
for i in arr:
    if i>15:
        l.append(i)
l=np.array(l)
print(l)

[20 25]


In [ ]:
arr>15

array([False, False, False,  True,  True])

In [ ]:
arr[arr>15]

array([20, 25])

### 4. Fancy Indexing

In [ ]:
arr=np.array([100,200,300,400,500])
indices=[0,2,4]
arr[indices]

array([100, 300, 500])

In [ ]:
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


In [ ]:
mat[mat>5]

array([6, 7, 8, 9])

In [ ]:
mat[[0,1],
    [2,2]]

array([3, 6])

### 5. Modifying with Indexing

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr[2]=10
arr

array([ 1,  2, 10,  4,  5,  6])

In [ ]:
arr[arr>2]=7
arr

array([1, 2, 7, 7, 7, 7])

### 6. Indexing with np.where()

In [ ]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
idx=np.where(arr>20)

In [ ]:
arr[idx]

array([30, 40, 50])

In [ ]:
a_list=[1,2,3]
b_list=[4,5,6]
print(a_list+b_list)

[1, 2, 3, 4, 5, 6]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
a*b

array([ 4, 10, 18])

In [ ]:
print(np.dot(a,b))

32


In [ ]:
a1=np.array([[1,2,3],[4,5,6]])
b2=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(a1.shape)
print(b2.shape)

(2, 3)
(2, 3)


In [ ]:
print(np.dot(a1,b2.T))

[[14 32]
 [32 77]]


In [ ]:
a1@b2.T

array([[14, 32],
       [32, 77]])

In [ ]:
# apple, banana, smartphone, toy, furniture
shop_sold_amazon = np.array([
    [100, 200, 20, 30, 5], # state-1-product-sold
    [200, 400, 40, 60, 10] # state-2-product-sold
])
print(shop_sold_amazon.shape)

(2, 5)


In [ ]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220] # state-2-price
])
print(price_amazon.shape)

(2, 5)


In [ ]:
price_amazon.T

array([[  30,   34],
       [  10,   12],
       [1000, 1100],
       [  10,   11],
       [ 200,  220]])

In [ ]:
answer1=np.dot(shop_sold_amazon,price_amazon.T)
answer1

array([[26300, 29230],
       [52600, 58460]])

In [ ]:
eye=np.eye(2)
eye

array([[1., 0.],
       [0., 1.]])

In [ ]:
print(np.sum(answer1*eye))

84760.0


# Aggregation function

In [ ]:
a1=np.array([1,2,3,4,5])
print(np.sum(a1))

15


In [ ]:
np.min(a1)

np.int64(1)

In [ ]:
np.max(a1)

np.int64(5)

In [ ]:
# index of the max element # not aggresation funct
a_3 = [5,2,100, 45, 450, 1, 5]
print(np.argmax(a_3))

4


In [ ]:
print(np.argmin(a_3))

5


In [ ]:
a_4=np.array([
    [10,20,30,40,50],
    [10,20,30,40,50],
    [10,20,30,40,50],
    [10,20,30,40,50]
])

In [ ]:
np.sum(a_4)

np.int64(600)

In [ ]:
np.sum(a_4,axis=0)
# axis->0 means sum over rows, keep columns

array([ 40,  80, 120, 160, 200])

In [ ]:
np.sum(a_4,axis=1)
# axis->1 means sum over columns, keep rows

array([150, 150, 150, 150])

In [ ]:
np.mean(a_4)

np.float64(30.0)

In [ ]:
np.mean(price_amazon)

np.float64(262.7)

In [ ]:
np.mean(a_4,axis=0)

array([10., 20., 30., 40., 50.])

In [ ]:
np.std(a_4,axis=1)

array([14.14213562, 14.14213562, 14.14213562, 14.14213562])

In [ ]:
np.var(a_4,axis=1)

array([200., 200., 200., 200.])

In [ ]:
np.cumsum(a_4,axis=1)

array([[ 10,  30,  60, 100, 150],
       [ 10,  30,  60, 100, 150],
       [ 10,  30,  60, 100, 150],
       [ 10,  30,  60, 100, 150]])

In [ ]:
np.median(a_4,axis=0)

array([10., 20., 30., 40., 50.])

In [ ]:
a4=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(a4,50))

5.5


# sort, search, counting functions

In [ ]:
a5=np.array([6,5,7,4,8,3,9,2,0,1,1])
len(a5)

11

In [ ]:
print("Sorted Array is : ",np.sort(a5))
print("Sorted Index's are : ",np.argsort(a5))

Sorted Array is :  [0 1 1 2 3 4 5 6 7 8 9]
Sorted Index's are :  [ 8  9 10  7  5  3  1  0  2  4  6]


Instead of returning the sorted values themselves, 

it returns an array of indices that, when used to index the original array, would produce a sorted sequence.

In [ ]:
print("search postion is :",np.searchsorted(sorted(a5),4))
print("unique elemts are :",np.unique(a5))
print("counts of bits are : ",np.bincount(a5))  ##max 8 and Min 0

search postion is : 5
unique elemts are : [0 1 2 3 4 5 6 7 8 9]
counts of bits are :  [1 2 1 1 1 1 1 1 1 1]


In [ ]:
arr_new=np.array([1,6,7,8,5,4,3,2,1,5,3,2])
arr_new

array([1, 6, 7, 8, 5, 4, 3, 2, 1, 5, 3, 2])

In [ ]:
arr=np.array([1,2,3,4])
for i in arr:
    print(i)

1
2
3
4


In [ ]:
arr_2d=np.array([[1,2],[3,4]])
for i in arr_2d:
    print(i)

[1 2]
[3 4]


In [ ]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr=np.arange(8).reshape(2,2,2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
arr.ndim

3

In [ ]:
for i in arr:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7


In [ ]:
a=np.array([1,2,3])

In [ ]:
b=a

In [ ]:
print(id(a))
print(id(b))

2402229256432
2402229256432


In [ ]:
b[0]=100

In [ ]:
print(a)

[100   2   3]


In [ ]:
b=a.copy()

In [ ]:
print(id(a))
print(id(b))

2402229256432
2402232202896


In [ ]:
a=np.array([1,2,3,4])
b=a.view()

In [ ]:
print(id(a))
print(id(b))

2402232196848
2402231110032


In [ ]:
print(np.shares_memory(a,b))

True


In [ ]:
a=np.array([[1,2]])
b=np.array([[3,4]])

In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [ ]:
np.hstack((a,b))

array([[1, 2, 3, 4]])

# numpy char and strings

In [ ]:
a=np.array(["hello ", "world "])
b=np.array(['123','user'])
print(np.char.add(a,b))

['hello 123' 'world user']


In [ ]:
print(np.char.multiply(a,2))

['hello hello ' 'world world ']


In [ ]:
print(np.char.lower(a))
print(np.char.upper(a))
print(np.char.capitalize(a))

['hello ' 'world ']
['HELLO ' 'WORLD ']
['Hello ' 'World ']


In [ ]:
print(np.char.center(a,11,fillchar="*"))

['***hello **' '***world **']


In [ ]:
def strchar(s):
    p=np.array([s[-4:]])
    print(p)
    print(np.char.center(s,30,fillchar="*"))


In [ ]:
strchar("helloworld")

['orld']
**********helloworld**********


In [ ]:
print(np.char.replace(a," ","_"))

['hello_' 'world_']


In [ ]:
a=np.array(["data science","machine learning"])
print(np.char.split(a," "))

[list(['data', 'science']) list(['machine', 'learning'])]


In [ ]:
print(np.char.find(a,"learn"))

[-1  8]


In [ ]:
print(np.char.count(a,"a"))

[2 2]
