# Numpy

Python lists are : 
 - Flexible but slowfor numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use numpy?
- Fast than pure python for numerical computation
- Vectorized operation (no explicit loops)
- Broadcasting (operate on arrays of different shape)
- Memory efficient
- Comes with powerful linear algebra, random tools etc

Use of numpy :
- Scientific python

In [217]:
import numpy as np

# creating arrays in numpy



### 1. np.array()

In [218]:
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [219]:
arr1

array([1, 2, 3, 4])

In [220]:
type(arr1[0])

numpy.int64

In [221]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [222]:
arr2[0]

array([1, 2, 3])

In [223]:
arr2[0][2]

np.int64(3)

In [224]:
arr2[1][2]

np.int64(6)

In [225]:
arr3=np.array([1,2,3,"Hello"])
print(arr3)
print(type(arr3))

['1' '2' '3' 'Hello']
<class 'numpy.ndarray'>


In [226]:
print(type(arr3[1]))

<class 'numpy.str_'>


In [227]:
arr4=np.array([1,2,3],dtype=np.int8)
print(type(arr4))

<class 'numpy.ndarray'>


In [228]:
print(type(arr4[0]))

<class 'numpy.int8'>


In [229]:
arr5=np.array([1,2,3,"Hello"],dtype=np.float16)

ValueError: could not convert string to float: 'Hello'

In [ ]:
arr6=np.array([1,2,3,"10"],dtype=np.float16)
arr6

<class 'numpy.float16'>


In [ ]:
print(type(arr6[3]))

<class 'numpy.float16'>


### 2. np.arange(start, stop, step)

In [ ]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [ ]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [ ]:
np_linespace_1=np.linspace(1,100,4)
print(np_linespace_1)
print(type(np_linespace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [ ]:
np_linespace_2=np.linspace(1,10,10)
print(np_linespace_2)
print(type(np_linespace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [ ]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
for i in np.linspace(1,10,10,dtype=np.int8):
    print(i)

1
2
3
4
5
6
7
8
9
10


### 4. np.zeros(shape)

shape -> shape of matrix

In [ ]:
npz_1=np.zeros(5)
npz_1

array([0., 0., 0., 0., 0.])

In [ ]:
npz_2=np.zeros((5,5),dtype=np.int8)
print(npz_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
npz_2=np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
npz_3=np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
npz_3.ndim

3

### 5. np.ones(shape)

shape -> shape of matrix

In [ ]:
np0=np.ones((2,3))
print(np0)

[[1. 1. 1.]
 [1. 1. 1.]]


### 6. np.full(shape, fill_value)

shape -> shape of matrix

In [ ]:
npf_1=np.full((2,3),10)
print(npf_1)

[[10 10 10]
 [10 10 10]]


### 7. np.eye(shape)

shape -> shape of matrix

- does not exist in 1D
- min of 2D,shape

In [ ]:
npe=np.eye(3)
npe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### 8. np.empty(shape)

In [ ]:
np.empty((2,2),dtype=np.int8)

array([[1, 0],
       [0, 1]], dtype=int8)

In [ ]:
np.empty((2,2),dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

### 9. np.random.rand(shape)

random values between 0 and 1

- ML weights random initialization

In [ ]:
np.random.rand(2,6)

array([[0.86216971, 0.14662251, 0.07209414, 0.64208939, 0.19102826,
        0.6764588 ],
       [0.59957656, 0.90164226, 0.17546328, 0.2876168 , 0.27844296,
        0.08711581]])

In [ ]:
# 1 D --> vector

# Numpy Array attributes

### 1. ndarray.shape

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


### 2. ndarray.ndim

In [ ]:
print(arr.ndim)

2


### 3. ndarray.size

Returns the total number of elements in the array.

In [ ]:
print(arr.size)

6


### 4. ndarray.dtype

Tells the data type of the array elements.

In [ ]:
print(arr.dtype)

int64


### 5. ndarray.itemsize

Returns the size in bytes of one element.

1 byte --> 8 bit

int8 --> 8 bit

int64 --> int8 * 8 --> int64

In [ ]:
print(arr.itemsize)

8


### 6. ndarray.nbytes
Total number of bytes consumed by the array.

In [ ]:
print(arr.nbytes)

48


### 7. ndarray.T

Returns the transpose of the array.

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)


In [ ]:
reshaped_1=arr.reshape(2,3)
print(reshaped_1)
print(reshaped_1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
reshaped_2=arr.reshape(3,2)
print(reshaped_2)
print(reshaped_2.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
reshaped_3=arr.reshape(1,6)
print(reshaped_3)
print(reshaped_3.ndim)

[[1 2 3 4 5 6]]
2


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(arr1.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


What reshape(3, -1) Means

3 → You are forcing the array to have 3 rows.

-1 → NumPy automatically calculates the number of columns.

-1 is not magic

In [ ]:
arr2=arr1.reshape(3,-1)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
arr3=arr1.reshape(-1,3)
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
arr4=arr1.reshape(2,-1)
print(arr4)
print(arr4.shape)


ValueError: cannot reshape array of size 9 into shape (2,newaxis)

# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

### 2. ravel() 

Flatten into 1D (returns a view)

Fast and memory-efficient.

Changes reflect in the original array (if no copy made).

In [ ]:
a=np.array([[1,2],[3,4]])

In [ ]:
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
print(a.ravel())

[1 2 3 4]


In [ ]:
print(a)

[[1 2]
 [3 4]]


In [ ]:
a_reval=a.ravel()
print(a_reval)
print(id(a))
print(id(a.ravel()))
print(id(a_reval))

[1 2 3 4]
2008818723952
2008818907824
2008818908880


In [ ]:
print("Data Address of 'a' : ",a.__array_interface__['data'][0])

Data Address of 'a' :  2008283247648


In [ ]:
print("Data Interfrence of Ravel a :",a.ravel().__array_interface__['data'][0])

Data Interfrence of Ravel a : 2008283247648


In [ ]:
print("Data Interfrence of Ravel a : ",a_reval.__array_interface__['data'][0])

Data Interfrence of Ravel a :  2008283247648


In [ ]:
a[0][0]=11

In [ ]:
a

array([[11,  2],
       [ 3,  4]])

In [ ]:
print(a_reval)

[11  2  3  4]


### 3. flatten()

Flatten into 1D (returns a copy)

In [ ]:
a

array([[11,  2],
       [ 3,  4]])

In [ ]:
b=a.flatten()

In [ ]:
b

array([11,  2,  3,  4])

In [ ]:
print("Data Interfrence of a : ",a.__array_interface__['data'][0])
print("Data Interfrence of b : ",b.__array_interface__['data'][0])

Data Interfrence of a :  2008283247648
Data Interfrence of b :  2008283244960


### 4. resize()

Resize Array In-place

Unlike reshape(), it can change total size. Data may be truncated or padded with zeros.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
a.resize(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.resize(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.resize(3,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.resize((3,3),refcheck=False)
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

### 5. squeeze()

Remove single-dimensional axes

Useful for removing extra dimensions from image or model output shapes like (1, 28, 28, 1)

In [ ]:
a=np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [ ]:
b=a.squeeze()

In [ ]:
print(b)
print(b.shape)

[1 2 3]
(3,)


| Function        | Purpose                        | In-place | Returns Copy/View  |
| --------------- | ------------------------------ | -------- | ------------------ |
| `reshape()`     | Change shape (same size)       | ❌        | View (if possible) |
| `resize()`      | Resize array (can change size) | ✅        | None               |
| `ravel()`       | Flatten array (1D)             | ❌        | View               |
| `flatten()`     | Flatten array (1D)             | ❌        | Copy               |
| `squeeze()`     | Remove dimensions of size 1    | ❌        | New array          |


# Indexing and Slicing in NumPy — Beginner to Advanced

###  1. Basic Indexing (1D Arrays)

Slicing syntax: array[start:stop:step]

In [ ]:
arr=np.array([10,20,30,40,50])

In [ ]:
print(arr[0])

10


In [ ]:
print(arr[-1])

50


In [ ]:
print(arr[4])

50


In [ ]:
print(arr[1:4])

[20 30 40]


In [ ]:
print(arr[1:-1])

[20 30 40]


In [ ]:
print(arr[0:3])

[10 20 30]


In [ ]:
print(arr[:3])

[10 20 30]


In [ ]:
print(arr[0:5:2])

[10 30 50]


In [ ]:
print(arr[::2])

[10 30 50]


In [ ]:
print(arr[::-1])

[50 40 30 20 10]


In [ ]:
list_1=[1,2,3,4,5,6,7]
list_1[::-1]

[7, 6, 5, 4, 3, 2, 1]

### 2. Indexing in 2D Arrays

In [ ]:
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
mat[0][1]

np.int64(2)

In [ ]:
mat[0,1]

np.int64(2)

In [ ]:
mat[:,2]

array([3, 6, 9])

In [ ]:
mat[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
mat[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 3. Boolean Indexing

In [ ]:
arr=np.array([5,10,15,20,25])

In [ ]:
l=[]
for i in arr:
    if i>15:
        l.append(i)
l=np.array(l)
print(l)

[20 25]


In [ ]:
arr>15

array([False, False, False,  True,  True])

In [ ]:
arr[arr>15]

array([20, 25])

### 4. Fancy Indexing

In [ ]:
arr=np.array([100,200,300,400,500])
indices=[0,2,4]
arr[indices]

array([100, 300, 500])

In [ ]:
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


In [ ]:
mat[mat>5]

array([6, 7, 8, 9])

In [ ]:
mat[[0,1],
    [2,2]]

array([3, 6])

### 5. Modifying with Indexing

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr[2]=10
arr

array([ 1,  2, 10,  4,  5,  6])

In [ ]:
arr[arr>2]=7
arr

array([1, 2, 7, 7, 7, 7])

### 6. Indexing with np.where()

In [230]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [233]:
idx=np.where(arr>20)

In [234]:
arr[idx]

array([30, 40, 50])

In [ ]:
a_list=[1,2,3]
b_list=[4,5,6]
print(a_list+b_list)

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)