# Numpy

Python lists are : 
 - Flexible but slowfor numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use numpy?
- Fast than pure python for numerical computation
- Vectorized operation (no explicit loops)
- Broadcasting (operate on arrays of different shape)
- Memory efficient
- Comes with powerful linear algebra, random tools etc

Use of numpy :
- Scientific python

In [4]:
import numpy as np

# creating arrays in numpy



### 1. np.array()

In [5]:
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
arr1

array([1, 2, 3, 4])

In [7]:
type(arr1[0])

numpy.int64

In [8]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
arr2[0]

array([1, 2, 3])

In [10]:
arr2[0][2]

np.int64(3)

In [11]:
arr2[1][2]

np.int64(6)

In [12]:
arr3=np.array([1,2,3,"Hello"])
print(arr3)
print(type(arr3))

['1' '2' '3' 'Hello']
<class 'numpy.ndarray'>


In [13]:
print(type(arr3[1]))

<class 'numpy.str_'>


In [14]:
arr4=np.array([1,2,3],dtype=np.int8)
print(type(arr4))

<class 'numpy.ndarray'>


In [15]:
print(type(arr4[0]))

<class 'numpy.int8'>


In [16]:
arr5=np.array([1,2,3,"Hello"],dtype=np.float16)

ValueError: could not convert string to float: 'Hello'

In [ ]:
arr6=np.array([1,2,3,"10"],dtype=np.float16)
arr6

<class 'numpy.float16'>


In [ ]:
print(type(arr6[3]))

<class 'numpy.float16'>


### 2. np.arange(start, stop, step)

In [ ]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [18]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [20]:
np_linespace_1=np.linspace(1,100,4)
print(np_linespace_1)
print(type(np_linespace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [23]:
np_linespace_2=np.linspace(1,10,10)
print(np_linespace_2)
print(type(np_linespace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [24]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [25]:
for i in np.linspace(1,10,10,dtype=np.int8):
    print(i)

1
2
3
4
5
6
7
8
9
10


### 4. np.zeros(shape)

shape -> shape of matrix

In [26]:
npz_1=np.zeros(5)
npz_1

array([0., 0., 0., 0., 0.])

In [29]:
npz_2=np.zeros((5,5),dtype=np.int8)
print(npz_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [31]:
npz_2=np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
npz_3=np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [33]:
npz_3.ndim

3

### 5. np.ones(shape)

shape -> shape of matrix

In [35]:
np0=np.ones((2,3))
print(np0)

[[1. 1. 1.]
 [1. 1. 1.]]


### 6. np.full(shape, fill_value)

shape -> shape of matrix

In [37]:
npf_1=np.full((2,3),10)
print(npf_1)

[[10 10 10]
 [10 10 10]]


### 7. np.eye(shape)

shape -> shape of matrix

- does not exist in 1D
- min of 2D,shape

In [40]:
npe=np.eye(3)
npe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [42]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [43]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### 8. np.empty(shape)

In [ ]:
np.empty((2,2),dtype=np.int8)

array([[1, 0],
       [0, 1]], dtype=int8)

In [53]:
np.empty((2,2),dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

### 9. np.random.rand(shape)

random values between 0 and 1

- ML weights random initialization

In [57]:
np.random.rand(2,6)

array([[0.86216971, 0.14662251, 0.07209414, 0.64208939, 0.19102826,
        0.6764588 ],
       [0.59957656, 0.90164226, 0.17546328, 0.2876168 , 0.27844296,
        0.08711581]])

In [ ]:
# 1 D --> vector

# Numpy Array attributes

### 1. ndarray.shape

In [66]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


### 2. ndarray.ndim

In [67]:
print(arr.ndim)

2


### 3. ndarray.size

Returns the total number of elements in the array.

In [69]:
print(arr.size)

6


### 4. ndarray.dtype

Tells the data type of the array elements.

In [71]:
print(arr.dtype)

int64


### 5. ndarray.itemsize

Returns the size in bytes of one element.

1 byte --> 8 bit

int8 --> 8 bit

int64 --> int8 * 8 --> int64

In [74]:
print(arr.itemsize)

8


### 6. ndarray.nbytes
Total number of bytes consumed by the array.

In [75]:
print(arr.nbytes)

48


### 7. ndarray.T

Returns the transpose of the array.

In [79]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [80]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

In [82]:
arr=np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)


In [85]:
reshaped_1=arr.reshape(2,3)
print(reshaped_1)
print(reshaped_1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [86]:
reshaped_2=arr.reshape(3,2)
print(reshaped_2)
print(reshaped_2.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [87]:
reshaped_3=arr.reshape(1,6)
print(reshaped_3)
print(reshaped_3.ndim)

[[1 2 3 4 5 6]]
2


In [90]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(arr1.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


What reshape(3, -1) Means

3 → You are forcing the array to have 3 rows.

-1 → NumPy automatically calculates the number of columns.

-1 is not magic

In [93]:
arr2=arr1.reshape(3,-1)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [94]:
arr3=arr1.reshape(-1,3)
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [95]:
arr4=arr1.reshape(2,-1)
print(arr4)
print(arr4.shape)


ValueError: cannot reshape array of size 9 into shape (2,newaxis)